-- NOTE: This file is auto generated by ./sql-generator

-- AiInterpretSearchRepository.upsert
insert into
  "ai_interpret_search" ("updatedAt")
values
  ($1)
on conflict ("assetId") do update
set
  "text" = "excluded"."text",
  "embedding" = "excluded"."embedding",
  "runKey" = "excluded"."runKey",
  "model" = "excluded"."model",
  "updatedAt" = "excluded"."updatedAt"

-- AiInterpretSearchRepository.get
select
  "assetId",
  "runKey",
  "model"
from
  "ai_interpret_search"
where
  "assetId" = $1

-- AiInterpretSearchRepository.getStoredByAssetIds
select
  "assetId",
  "runKey",
  "model"
from
  "ai_interpret_search"
where
  "assetId" in ($1)

-- AiInterpretSearchRepository.pageAssetsWithRuns
select
  "assetId",
  "value"
from
  "asset_metadata"
where
  "key" = $1
  and "assetId" > $2
  and exists (
    select
      1
    from
      jsonb_each(asset_metadata.value -> 'runs') as run
    where
      run.value ->> 'status' = 'completed'
  )
order by
  "assetId" asc
limit
  $3

-- AiInterpretSearchRepository.searchDense
begin
set
  local vchordrq.probes = 1
select
  "ai_interpret_search"."assetId",
  ai_interpret_search.embedding <=> $1 as "distance"
from
  "ai_interpret_search"
  inner join "asset" on "asset"."id" = "ai_interpret_search"."assetId"
where
  "asset"."ownerId" in ($2)
  and "asset"."deletedAt" is null
  and "asset"."visibility" != $3
  and 1 - (ai_interpret_search.embedding <=> $4) >= $5
order by
  "distance" asc,
  "ai_interpret_search"."assetId" asc
limit
  $6
commit

-- AiInterpretSearchRepository.searchLexical
select
  "ai_interpret_search"."assetId",
  f_unaccent (ai_interpret_search.text) <->>> f_unaccent ($1) as "distance"
from
  "ai_interpret_search"
  inner join "asset" on "asset"."id" = "ai_interpret_search"."assetId"
where
  "asset"."ownerId" in ($2)
  and "asset"."deletedAt" is null
  and "asset"."visibility" != $3
  and f_unaccent (ai_interpret_search.text) %>> f_unaccent ($4)
order by
  "distance" asc,
  "ai_interpret_search"."assetId" asc
limit
  $5
