-- NOTE: This file is auto generated by ./sql-generator

-- PdfRepository.getAssetForProcessing
select
  "asset"."id",
  "asset"."ownerId",
  "asset"."originalPath",
  "asset"."originalFileName",
  "asset"."type",
  "asset"."deletedAt"
from
  "asset"
where
  "asset"."id" = $1

-- PdfRepository.streamPdfAssetIds
select
  "asset"."id"
from
  "asset"
  left join "pdf_document" on "pdf_document"."assetId" = "asset"."id"
where
  "asset"."type" = $1
  and "asset"."deletedAt" is null
  and lower("asset"."originalFileName") like '%.pdf'
  and "pdf_document"."assetId" is null

-- PdfRepository.upsertDocument
insert into
  "pdf_document" (
    "assetId",
    "pageCount",
    "title",
    "author",
    "subject",
    "creator",
    "producer",
    "creationDate",
    "processedAt",
    "status",
    "lastError"
  )
values
  ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
on conflict ("assetId") do update
set
  "pageCount" = "excluded"."pageCount",
  "title" = "excluded"."title",
  "author" = "excluded"."author",
  "subject" = "excluded"."subject",
  "creator" = "excluded"."creator",
  "producer" = "excluded"."producer",
  "creationDate" = "excluded"."creationDate",
  "processedAt" = "excluded"."processedAt",
  "status" = "excluded"."status",
  "lastError" = "excluded"."lastError"

-- PdfRepository.updateDocumentStatus
insert into
  "pdf_document" (
    "assetId",
    "status",
    "lastError",
    "processedAt",
    "pageCount"
  )
values
  ($1, $2, $3, $4, $5)
on conflict ("assetId") do update
set
  "status" = "excluded"."status",
  "lastError" = "excluded"."lastError",
  "processedAt" = "excluded"."processedAt"

-- PdfRepository.markDocumentReady
insert into
  "pdf_document" (
    "assetId",
    "status",
    "lastError",
    "processedAt",
    "pageCount"
  )
values
  ($1, $2, $3, $4, $5)
on conflict ("assetId") do update
set
  "status" = "excluded"."status",
  "lastError" = "excluded"."lastError",
  "processedAt" = "excluded"."processedAt"

-- PdfRepository.replacePages
begin
delete from "pdf_page"
where
  "assetId" = $1
insert into
  "pdf_page" ("pageNumber", "text")
values
  ($1, $2)
rollback

-- PdfRepository.upsertSearch
insert into
  "pdf_search" ("assetId", "text")
values
  ($1, $2)
on conflict ("assetId") do update
set
  "text" = "excluded"."text"

-- PdfRepository.getDocumentsByOwner
select
  "asset"."id" as "assetId",
  "asset"."originalFileName",
  "asset"."fileCreatedAt" as "createdAt",
  "asset"."fileModifiedAt" as "updatedAt",
  "pdf_document"."pageCount",
  "pdf_document"."title",
  "pdf_document"."author",
  "pdf_document"."processedAt",
  "pdf_document"."status",
  "pdf_document"."lastError"
from
  "asset"
  left join "pdf_document" on "pdf_document"."assetId" = "asset"."id"
where
  "asset"."ownerId" = $1
  and "asset"."type" = $2
  and "asset"."deletedAt" is null
  and lower("asset"."originalFileName") like '%.pdf'
  and coalesce("pdf_document"."status", 'pending') = $3
order by
  "asset"."fileCreatedAt" desc
limit
  $4
offset
  $5

-- PdfRepository.getDocumentStatusSummaryByOwner
select
  coalesce("pdf_document"."status", 'pending') as "status",
  count(*)::int as "count"
from
  "asset"
  left join "pdf_document" on "pdf_document"."assetId" = "asset"."id"
where
  "asset"."ownerId" = $1
  and "asset"."type" = $2
  and "asset"."deletedAt" is null
  and lower("asset"."originalFileName") like '%.pdf'
group by
  coalesce("pdf_document"."status", 'pending')

-- PdfRepository.getDocumentByOwner
select
  "asset"."id" as "assetId",
  "asset"."originalFileName",
  "asset"."fileCreatedAt" as "createdAt",
  "asset"."fileModifiedAt" as "updatedAt",
  "pdf_document"."pageCount",
  "pdf_document"."title",
  "pdf_document"."author",
  "pdf_document"."processedAt",
  "pdf_document"."status",
  "pdf_document"."lastError"
from
  "asset"
  left join "pdf_document" on "pdf_document"."assetId" = "asset"."id"
where
  "asset"."ownerId" = $1
  and "asset"."id" = $2
  and "asset"."deletedAt" is null
  and lower("asset"."originalFileName") like '%.pdf'

-- PdfRepository.getPagesByOwner
select
  "pdf_page".*
from
  "pdf_page"
  inner join "asset" on "asset"."id" = "pdf_page"."assetId"
where
  "asset"."ownerId" = $1
  and "asset"."id" = $2
order by
  "pdf_page"."pageNumber" asc

-- PdfRepository.getPageByOwner
select
  "pdf_page".*
from
  "pdf_page"
  inner join "asset" on "asset"."id" = "pdf_page"."assetId"
where
  "asset"."ownerId" = $1
  and "asset"."id" = $2
  and "pdf_page"."pageNumber" = $3

-- PdfRepository.searchByText
select
  "asset"."id" as "assetId",
  "asset"."originalFileName",
  "asset"."fileCreatedAt" as "createdAt",
  "asset"."fileModifiedAt" as "updatedAt",
  "pdf_document"."pageCount",
  "pdf_document"."title",
  "pdf_document"."author",
  "pdf_document"."processedAt",
  "pdf_document"."status",
  "pdf_document"."lastError"
from
  "pdf_search"
  inner join "asset" on "asset"."id" = "pdf_search"."assetId"
  left join "pdf_document" on "pdf_document"."assetId" = "asset"."id"
where
  "asset"."ownerId" = $1
  and "asset"."deletedAt" is null
  and coalesce("pdf_document"."status", 'pending') = $2
  and f_unaccent ("pdf_search"."text") %>> f_unaccent ($3)
order by
  "asset"."fileCreatedAt" desc
limit
  $4
offset
  $5

-- PdfRepository.getMatchingPagesByAssets
select
  "assetId",
  "pageNumber"
from
  "pdf_page"
where
  "assetId" in ($1)
  and f_unaccent ("pdf_page"."text") %>> f_unaccent ($2)
order by
  "assetId" asc,
  "pageNumber" asc

-- PdfRepository.searchPagesByOwner
select
  "pdf_page"."pageNumber",
  "pdf_page"."text"
from
  "pdf_page"
  inner join "asset" on "asset"."id" = "pdf_page"."assetId"
where
  "asset"."ownerId" = $1
  and "asset"."id" = $2
  and f_unaccent ("pdf_page"."text") %>> f_unaccent ($3)
order by
  "pdf_page"."pageNumber" asc
limit
  $4
